apiVersion: v1
kind: Service
metadata:
  name: agent-tester
  labels:
    app: tester-microservice
    role: tester
    tier: backend
    group: agent-tester-microservice
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  # type: NodePort 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 9300
    protocol: TCP
    name: http
  - port: 9210
    protocol: TCP
    name: https
  selector:
    app: tester-microservice
    role: tester
    tier: backend
    group: agent-tester-microservice