version: "3.6"
services:

  va.testing.microservice:
    container_name: testing-microservice
    build: .
    image: ibm/testing/va.testing.microservice:dev
    networks:
      - tester-bundle
    ports:
      - "9060:9080"
      - "9200:9443"
    environment:
      #Connection and microservice variables
      - REST_ADMIN_USERNAME=myRestAdminUser
      - REST_ADMIN_PASSWORD=myRestAdminPassword
      - TESTER_WEBHOOK_USERNAME=testerWebhookUser
      - TESTER_WEBHOOK_PASSWORD=testerWebhookPassword
      - TESTER_WEBHOOK_URI=${TESTER_WEBHOOK_URI}
      #Cloudant variables
      - CLOUDANT_URL=${CLOUDANT_URL}
      - CLOUDANT_USERNAME=${CLOUDANT_USERNAME}
      - CLOUDANT_PASSWORD=${CLOUDANT_PASSWORD}
      - CLOUDANT_DATABASE_NAME=${CLOUDANT_DATABASE_NAME}
      # Voice Gateway User Agent Client variables
      - CALLER_VOICE_GATEWAY_URI=${CALLER_VOICE_GATEWAY_URI}
      - CALLER_VOICE_GATEWAY_USERNAME=${CALLER_VOICE_GATEWAY_USERNAME}
      - CALLER_VOICE_GATEWAY_PASSWORD=${CALLER_VOICE_GATEWAY_PASSWORD}
      # Logging variables
      - LOG_LEVEL=all
      - LOG_MAX_FILE_SIZE=100
      - LOG_MAX_FILES=10

    volumes:
      - ./bundle/logs/MS:/logs
      - ./bundle/tester_credentials:/custom_registry
    
  sip.orchestrator:
    image: ibmcom/voice-gateway-so:latest
    container_name: voice-gateway-so-tester
    networks:
      - tester-bundle
    ports:
      - "9100:9080"
      - "9110:9443"
      - "5060:5060"
      - "5060:5060/udp"
    environment:
      # Host name of the CMR.
      - MEDIA_RELAY_HOST=media.relay:8080
      - SIP_HOST=${EXTERNAL_IP}
      - HTTP_HOST=*
      - REST_API_USERNAME=${CALLER_VOICE_GATEWAY_USERNAME}
      - REST_API_PASSWORD=${CALLER_VOICE_GATEWAY_PASSWORD}

      - ENABLE_OUTBOUND_CALLS=true
      # Logging related variables
      - ENABLE_TRANSCRIPTION_AUDIT_MESSAGES=true
      - LOG_LEVEL=all
      - LOG_MAX_FILE_SIZE=100
      - LOG_MAX_FILES=10
    volumes:
      - ./bundle/logs/SO:/logs

  media.relay:
    image: ibmcom/voice-gateway-mr:latest
    container_name: voice-gateway-mr-tester
    networks:
      - tester-bundle
    ports:
      - "16334-16394:16334-16394/udp"
    environment:
      - SDP_ADDRESS=${EXTERNAL_IP}
      - RTP_UDP_PORT_RANGE=16334-16394
      - MEDIA_RELAY_LOG_LEVEL=DEBUG
      - MEDIA_RELAY_WS_PORT=8080
      - STT_TRACK_LATENCY=true

      # API Key of your IBM Cloud Speech-To-Text Service instance
      - WATSON_STT_APIKEY=${WATSON_STT_APIKEY}
      # URL of your IBM Cloud Speech-To-Text Service instance
      - WATSON_STT_URL=


      # API Key of your IBM Cloud Text-To-Speech Service instance
      - WATSON_TTS_APIKEY=
      # URL of your IBM Cloud Text-To-Speech Service instance
      - WATSON_TTS_URL=

      - WATSON_TTS_VOICE=en-US_MichaelV2Voice
      
      # Comment to disable recording
      - ENABLE_RECORDING=true
    volumes:
      - ./bundle/recordings:/vgw-media-relay/recordings
      - ./bundle/logs/MR:/vgw-media-relay/logs

  couchdb:
    container_name: testing-data
    image: apache/couchdb:2.3.1
    networks:
      - tester-bundle
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./bundle/couchdb/couchDbData:/opt/couchdb/data

networks:
  tester-bundle:
    name: tester-bundle