---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-couchdb
  labels:
    volume: couch-volume
    group: agent-tester-microservice
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/tmp/couchdb"
